# Generated by Django 4.0.2 on 2022-03-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_signup_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
