# Generated by Django 4.0.2 on 2022-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
