# Generated by Django 4.0.4 on 2022-08-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_school_task_task_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
        migrations.AddField(
            model_name='task',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classroom'),
        ),
        migrations.AddField(
            model_name='task',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AddField(
            model_name='task',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
        migrations.CreateModel(
            name='Admin_Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_degree', models.CharField(max_length=200)),
                ('staff_address', models.CharField(max_length=200)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
    ]
