# Generated by Django 4.0.4 on 2022-05-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_student', models.IntegerField(max_length=20)),
                ('number_of_teacher', models.IntegerField(max_length=20)),
            ],
        ),
    ]
