# Generated by Django 4.0.4 on 2022-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='number_of_student',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_teacher',
            field=models.IntegerField(null=True),
        ),
    ]
