# Generated by Django 4.0.2 on 2022-04-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
